const {
  REACT_APP_PROJECT_ID: PROJECT_ID,
  REACT_APP_GROSS_PROFIT_MEASURE: GROSS_PROFIT_MEASURE,
  REACT_APP_DATE_ATTRIBUTE_IN_MONTHS: DATE_ATTRIBUTE_IN_MONTHS,
  REACT_APP_DATE_ATTRIBUTE: DATE_ATTRIBUTE
} = process.env;

export {
  PROJECT_ID,
  GROSS_PROFIT_MEASURE,
  DATE_ATTRIBUTE,
  DATE_ATTRIBUTE_IN_MONTHS
};